sys:
  env: dev
spring:
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 'x'
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 21b60067-97cb-4da4-86a5-1798a69b059e
dubbo:
  scan:
    basePackages: com.moda
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    accesslog: true
    port: -1
  provider:
    timeout: 6000
    validation: true
  consumer:
    timeout: 6000
    check: false
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    default-executor-type: simple
    map-underscore-to-camel-case: true
    local-cache-scope: session
    jdbc-type-for-null: null
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}