gateway:
  auth-access: false
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:1902
      eager: true
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: moda-demo-api
          uri: lb://moda-demo-api
          predicates:
            - Path=/demo/**
          filters:
            - RewritePath=/demo/(?<segment>.*), /$\{segment}