global:
  scrape_interval: 15s
  evaluation_interval: 30s
  scrape_timeout: 10s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
rule_files:
  - "service_off_rules.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets:
      - localhost:20002
      - localhost:21002
      - localhost:22002
      - localhost:23002