server:
  port: 21001
swagger:
  title: 演示接口
  description: 测试一下
  version: 1.0
  base-package: com.moda.demo
  contact:
    name: lyh
    url: http://a.com
    email: lyh@a.com
spring:
  cloud:
    sentinel:
      transport:
        port: 3911
management:
  server:
    port: 21002